### ISSUE TITLE
Visibility of data

### ISSUE THREAD

**Issue by VenomFate-619** [championswimmer/awesome-devs#1]
Sir, update dev info in readme or make a website that will parse data from YAML  (I would like to help you to make website if required )

**Comment by championswimmer** [comment]
@VenomFate-619 yeah yeah that is the idea, if you make a script or simple frontend website to do that, would love to 

I just setup the repo yesterday, the next step is to make the data visible

**Comment by championswimmer** [comment]
Data visible now 

https://championswimmer.in/awesome-devs
